# Generated by Django 5.2.5 on 2025-08-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparelhos', '0003_grupo_muscular_alter_aparelho_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelho',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='aparelhos/'),
        ),
    ]
