# Generated by Django 5.2.5 on 2025-08-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparelhos', '0004_aparelho_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelho',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='aparelhos/videos/'),
        ),
    ]
