# Generated by Django 5.2.5 on 2025-10-01 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparelhos', '0005_aparelho_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Avaliação de 1 a 5 estrelas')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aparelho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='aparelhos.aparelho')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'aparelho')},
            },
        ),
        migrations.CreateModel(
            name='Visualizacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('aparelho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='aparelhos.aparelho')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'aparelho')},
            },
        ),
    ]
