# Generated by Django 5.2.5 on 2025-10-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparelhos', '0006_feedback_visualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizacao',
            name='count',
            field=models.PositiveIntegerField(default=1, help_text='Número de visualizações'),
        ),
        migrations.AddField(
            model_name='visualizacao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
