# Generated by Django 5.2.5 on 2025-10-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparelhos', '0007_visualizacao_count_visualizacao_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizacao',
            name='last_clicked',
            field=models.DateTimeField(blank=True, help_text='Última vez que o usuário clicou no botão', null=True),
        ),
    ]
