# Generated by Django 5.2.5 on 2025-10-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparelhos', '0008_visualizacao_last_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelho',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR Code gerado automaticamente', null=True, upload_to='aparelhos/qrcodes/'),
        ),
    ]
