# Generated by Django 5.2.5 on 2026-08-14 11:11

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparelhos', '0010_grupos_musculares_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelho',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='aparelhos/'),
        ),
        migrations.AlterField(
            model_name='aparelho',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR Code gerado automaticamente', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='aparelhos/qrcodes/'),
        ),
        migrations.AlterField(
            model_name='aparelho',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='aparelhos/videos/'),
        ),
    ]
