# Generated by Django 5.2.5 on 2025-08-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparelhos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparelho',
            name='factory_year',
        ),
        migrations.RemoveField(
            model_name='aparelho',
            name='model',
        ),
        migrations.RemoveField(
            model_name='aparelho',
            name='model_year',
        ),
        migrations.RemoveField(
            model_name='aparelho',
            name='value',
        ),
        migrations.AddField(
            model_name='aparelho',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Exercício'),
        ),
        migrations.AddField(
            model_name='aparelho',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Instruções de Execução'),
        ),
        migrations.AlterField(
            model_name='aparelho',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
