# Generated by Django 5.2.5 on 2025-08-21 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparelhos', '0002_remove_aparelho_factory_year_remove_aparelho_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo_muscular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo Muscular',
                'verbose_name_plural': 'Grupos Musculares',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='aparelho',
            options={'ordering': ['exercise_name']},
        ),
        migrations.AlterField(
            model_name='aparelho',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='aparelho',
            name='grupo_muscular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aparelhos', to='aparelhos.grupo_muscular'),
        ),
    ]
